CREATE TABLE IF NOT EXISTS `%PREFIX%elements` (
  `id` int unsigned NOT NULL auto_increment,
  `element_set_id` int unsigned NOT NULL,
  `order` int unsigned default NULL,
  `name` varchar(255) collate utf8_unicode_ci NOT NULL,
  `description` text collate utf8_unicode_ci,
  `comment` text collate utf8_unicode_ci,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `name_element_set_id` (`element_set_id`,`name`),
  UNIQUE KEY `order_element_set_id` (`element_set_id`,`order`),
  KEY `element_set_id` (`element_set_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `%PREFIX%elements` VALUES 
(1, 3, NULL, 'Text', 'Any textual data included in the document. Copy and paste the text from the OCR document (.txt format) into this field. Alternately, this field may include a transcription of the document, in which case, try to capture the text as it is originally represented.
', NULL),
(2, 3, NULL, 'Interviewer', 'The person(s) performing the interview', NULL),
(3, 3, NULL, 'Interviewee', 'The person(s) being interviewed', NULL),
(4, 3, NULL, 'Location', 'The location of the interview', NULL),
(5, 3, NULL, 'Transcription', 'Any written text transcribed from a sound', NULL),
(6, 3, NULL, 'Local URL', 'The URL of the local directory containing all assets of the website', NULL),
(7, 3, NULL, 'Original Format', 'The type of object in its original form, such as paper, VHS, DVD, digital file. There is no controlled vocabulary for this, so use a term that best describes the format of the original object, before it has been scanned or digitized. Be as descriptive as possible. If there are multiple objects in the item record, create a separate entry for each one.', NULL),
(10, 3, NULL, 'Physical Dimensions', 'The actual physical size of the original image', NULL),
(11, 3, NULL, 'Duration', 'Length of time involved (seconds, minutes, hours, days, class periods, etc.). Use the format hh:mm:ss (eg: 00:15:04). If you have multiple parts (for example a video divided into three segments), create a label and list each one as a separate entry. (eg: Part 1 - 00:15:04, Part 2 - 00:07:58)', NULL),
(12, 3, NULL, 'Compression', 'Type/rate of compression for moving image file; most will be MP4 files (eg: video/mp4).', NULL),
(13, 3, NULL, 'Producer', 'Name (or names) of the person who produced the video.  Enter names according to SCKLS "General Input Guidelines" or recommended vocabularies. If there are multiple people, create a separate entry for each person.', NULL),
(14, 3, NULL, 'Director', 'Name (or names) of the person who produced the video', NULL),
(15, 3, NULL, 'Bit Rate/Frequency', 'Rate at which bits are transferred (i.e. 96 kbit/s would be FM quality audio)', NULL),
(16, 3, NULL, 'Time Summary', 'A summary of an interview given for different time stamps throughout the interview', NULL),
(17, 3, NULL, 'Email Body', 'The main body of the email, including all replied and forwarded text and headers', NULL),
(18, 3, NULL, 'Subject Line', 'The content of the subject line of the email', NULL),
(19, 3, NULL, 'From', 'The name and email address of the person sending the email', NULL),
(20, 3, NULL, 'To', 'The name(s) and email address(es) of the person to whom the email was sent', NULL),
(21, 3, NULL, 'CC', 'The name(s) and email address(es) of the person to whom the email was carbon copied', NULL),
(22, 3, NULL, 'BCC', 'The name(s) and email address(es) of the person to whom the email was blind carbon copied', NULL),
(23, 3, NULL, 'Number of Attachments', 'The number of attachments to the email', NULL),
(24, 3, NULL, 'Standards', '', NULL),
(25, 3, NULL, 'Objectives', '', NULL),
(26, 3, NULL, 'Materials', '', NULL),
(27, 3, NULL, 'Lesson Plan Text', '', NULL),
(28, 3, NULL, 'URL', '', NULL),
(29, 3, NULL, 'Event Type', '', NULL),
(30, 3, NULL, 'Participants', 'Names of individuals or groups participating in the event', NULL),
(31, 3, NULL, 'Birth Date', '', NULL),
(32, 3, NULL, 'Birthplace', '', NULL),
(33, 3, NULL, 'Death Date', '', NULL),
(34, 3, NULL, 'Occupation', '', NULL),
(35, 3, NULL, 'Biographical Text', '', NULL),
(36, 3, NULL, 'Bibliography', '', NULL),
(37, 1, 8, 'Contributor', 'An entity responsible for making contributions to the resource', NULL),
(38, 1, 15, 'Coverage', 'The spatial or temporal topic of the resource, the spatial applicability of the resource, or the jurisdiction under which the resource is relevant', NULL),
(39, 1, 4, 'Creator', 'All names must comply with SCKLS "General Input Guidelines".', NULL),
(40, 1, 7, 'Date', 'Date of creation of the original resource (before it underwent any conversions). All dates must comply with SCKLS "General Input Guidelines" (e.g. yyyy-mm-dd).', NULL),
(41, 1, 3, 'Description', 'Descriptive remarks or comments about the resource, such as a table of contents, abstract, or free text account of the content. This could also be contextual information that helps the user interpret the resource, provenance, or anything significant about the resource that is not covered elsewhere.', NULL),
(42, 1, 11, 'Format', 'The file format, physical medium, or dimensions of the resource', NULL),
(43, 1, 14, 'Identifier', 'An unambiguous reference to the resource within a given context', NULL),
(44, 1, 12, 'Language', 'A language of the resource', NULL),
(45, 1, 6, 'Publisher', 'The organization that is providing access to the digital object via the digital collection. This is usually the name of the library managing the digital collection.', NULL),
(46, 1, 10, 'Relation', 'The formal or informal group of objects to which a resource belongs, such as a series or collection. If the same item is found in a different format or location, include a link (URL) to the related item or collection.', NULL),
(47, 1, 9, 'Rights', 'Example: Reproduced with permission from the copyright owner. Further reproduction prohibited without permission. Example: Item is believed to be in the public domain. See SCKLS "Rights Statements" document for more information.', NULL),
(48, 1, 5, 'Source', 'This refers to a citation or reference to the physical location of the original resource. This may be specific location such as a call number or citation, or simply the name of the organization in which the original resource is housed. If the original resource is "born digital" and derives from no pre-existing print resource, you may include a link (URL) to the digital item, if it exists. See SCKLS "Dublin Core Metadata Use Guide" for more information.', NULL),
(49, 1, 2, 'Subject', 'Use a controlled vocabulary, such as Library of Congress Subject Headings or an in-house vocabulary list specific to your collection.  Consistency is imperative!', NULL),
(50, 1, 1, 'Title', 'See SCKLS "Dublin Core Metadata Use Guide" for more information on Titles.', NULL),
(51, 1, 13, 'Type', 'The nature or genre of the resource', NULL);
